spring.application.name=photoalbum

spring.datasource.url=jdbc:postgresql://localhost:5432/photoalbum_db
spring.datasource.username=postgres
spring.datasource.password=katty

spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false